# set complier
if(UNIX)
	if(CPU STREQUAL "X86")    
		set(CMAKE_CXX_COMPILER "g++")
	elseif(CPU STREQUAL "ARMHF" OR CPU STREQUAL "ARMHF")
		if(BITS STREQUAL 32)		
			set(CMAKE_CXX_COMPILER "arm-linux-gnueabihf-g++")
		else()
			set(CMAKE_CXX_COMPILER "aarch64-linux-gnu-g++")
		endif()
	elseif(CPU STREQUAL MIPS)
			set(CMAKE_CXX_COMPILER "mipsel-linux-gnu-g++")
    elseif(CPU STREQUAL TI)
			set(CMAKE_CXX_COMPILER "${CMAKE_CURRENT_LIST_DIR}/..//toolchain/tx2/gcc-linaro-7.5.0/bin/arm-linux-gnueabihf-g++")
	elseif(CPU STREQUAL NVIDIA)
            set(CMAKE_CXX_COMPILER "${CMAKE_CURRENT_LIST_DIR}/../toolchain/tx2/gcc-linaro-7.5.0/bin/aarch64-linux-gnu-g++")
	elseif(CPU STREQUAL "hypatia")
			MESSAGE(STATUS "set hypatia env ...")
			set(CMAKE_CXX_COMPILER "${CMAKE_CURRENT_LIST_DIR}/../toolchain/hypatia/toolchain-sunxi-glibc/toolchain/bin/arm-openwrt-linux-g++")
	endif()		
endif()

# set flags
if(UNIX)	
	add_compile_options(-fPIC -Wall -std=c++14)	
	if(CPU STREQUAL "X86")    
		if(BITS STREQUAL 32)
			add_compile_options(-m32)	
		else()
			add_compile_options(-m64)		
		endif()
	endif()			
endif()
