include_directories(${PROJECT_SOURCE_DIR}/include/)
include_directories(${PROJECT_SOURCE_DIR}/../../eSPDI/)

link_directories(${PROJECT_SOURCE_DIR}/lib/x86_64/)
link_directories(${PROJECT_SOURCE_DIR}/../../eSPDI/)
# if(CPU STREQUAL "X86")    
#     link_directories(${PROJECT_SOURCE_DIR}/lib/x86_64/)
# elseif(CPU STREQUAL TI)
#     link_directories(${PROJECT_SOURCE_DIR}/lib/armhf_ti_32/)
# elseif(CPU STREQUAL NVIDIA)
#     link_directories(${PROJECT_SOURCE_DIR}/lib/armhf_32/)
# elseif(CPU STREQUAL "hypatia")
#     link_directories(${PROJECT_SOURCE_DIR}/lib/TX2/)
# endif()		
