include(${CMAKE_CURRENT_LIST_DIR}/set_path_definition.cmake)

include_directories(${ESPDI_SOURCE_PATH})
include_directories(${ESPDI_SOURCE_PATH}/include)
include_directories(${FISHEYEDIR}/include)
include_directories(${FILTER_DIR}/include)
include_directories(${COMPUTER_DIR})
include_directories(${POST_PROCESS_DIR}/sources)
include_directories(${TURBOJPEG_INSTALL_PATH}/include)
include_directories(${WATCHDOG_DIR}/include)
include_directories(${OPENCL_INSTALL_PATH}/include)
include_directories(${ALSA_INSTALL_PATH}/include)
include_directories(${OPENCV_INSTALL_PATH}/include/opencv4)

link_directories(${WATCHDOG_DIR}/lib)
link_directories(${TURBOJPEG_INSTALL_PATH}/lib)
link_directories(${OPENCL_INSTALL_PATH}/lib)
link_directories(${ALSA_INSTALL_PATH}/lib)
